import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import AnimatedContent from "~/components/AnimatedContent";
import AnimatedNav from "~/components/AnimatedNav";
import HomePage from "~/components/HomePage";
import SecondHome from "~/components/SecondHome";
import HomePageComponent from "~/components/home";
import { api } from "~/utils/api";

export default function Home() {
  // const hello = api.post.hello.useQuery({ text: "from tRPC" });
  const [height, setHeight] = useState(1);

  useEffect(() => {
    const handleResize = () => {
      setHeight(window.innerHeight);
      console.log("window.innerHeight", window.innerHeight);
    };

    // Initial adjustment
    handleResize();

    // Add event listener for window resize
    window.addEventListener("resize", handleResize);

    // Clean up the event listener on component unmount
    return () => {
      window.removeEventListener("resize", handleResize);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Josue R. Mata Portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className="w-screen bg-gradient-to-b from-slate-900 to-slate-700 text-gray-300"
        style={{
          height: `${height}px`,
        }}
      >
        {/* <HomePage /> */}
        <SecondHome />
      </main>
    </>
  );
}
