import Head from "next/head";

import { useEffect, useState } from "react";
import HomePage from "~/components/HomePage";

export default function Home() {
  const [height, setHeight] = useState(1);

  useEffect(() => {
    const handleResize = () => {
      setHeight(window.innerHeight);
    };

    // Initial adjustment
    handleResize();

    // Add event listener for window resize
    window.addEventListener("resize", handleResize);

    // Clean up the event listener on component unmount
    return () => {
      window.removeEventListener("resize", handleResize);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Josue R. Mata Portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className="w-screen bg-gradient-to-b from-slate-900 to-slate-700"
        style={{
          height: `${height}px`,
        }}
      >
        <HomePage />
      </main>
    </>
  );
}
